---
# tasks file for heartbeat

- name: Install ha.cf
  template:
    src: ha.cf.j2
    dest: /etc/ha.d/ha.cf

- name: Config | Check authkeys
  stat:
    path: /etc/ha.d/authkeys
  register: _stat_authkeys

- name: Debug | Authkeys stat
  debug:
    var: "_stat_authkeys.stat.exists"

- name: Config | Creater Authkeys
  shell: dd if=/dev/urandom count=4 2>/dev/null | openssl dgst -sha1 | awk '{ print $2 }'
  register: _drbd_heartbeat_authkeys
  when: _stat_authkeys.stat.exists == false

- name: Config | Set fact
  set_fact:
    drbd_hearbeat_authkeys: "{{ _drbd_heartbeat_authkeys['stdout'] }}"
  when: _stat_authkeys.stat.exists == false

- name: Install Authkeys
  template:
    src: authkeys.j2
    dest: /etc/ha.d/authkeys
    mode: '0600'
    owner: 'root'
    group: 'root'
  when: _stat_authkeys.stat.exists == false

- name: Install haresources
  template:
    src: haresources.j2
    dest: /etc/ha.d/haresources
    mode: '0600'
    owner: 'root'
    group: 'root'

- name: Floating ip | Assign ip script
  copy:
    src: assign-ip
    dest: /usr/local/bin/assign-ip
    owner: root
    group: root
    mode: '0755'

- name: RabbitMQ | RabbitMQ Script
  copy:
    src: RabbitMQ
    dest: /etc/ha.d/resource.d/RabbitMQ
    owner: root
    group: root
    mode: '0755'

- name: Systemd | Create systemd service
  template:
      src: assign-ip.service.j2
      dest: /etc/init.d/assign-ip
      mode: '0755'
      owner: 'root'
      group: 'root'
      
- name: Start heartbeat
  systemd:
    state: restarted
    name: heartbeat