---
- name: Setup | Install pip
  apt:
    name: python3-pip
    state: present

- name: Setup | Install docker-py
  pip:
    name: docker-py
    executable: pip3
    state: present

- name: Pull rabbitmq Image managemenent
  docker_image:
    name: rabbitmq:3-management
    source: pull

# - name: Pull rabbitmq Imag
#   docker_image:
#     name: rabbitmq:3
#     source: pull

- name: Create rabbitmq network
  docker_network:
    name: rabbitmq

- name: Create rabbitmq container node1
  docker_container:
    name: rabbitmq-node1
    image: rabbitmq:3-management
    hostname: "node1"
    networks:
      - name: rabbitmq
    env:
      RABBITMQ_ERLANG_COOKIE: "secret_cookie"
      RABBITMQ_NODENAME: "rabbitmq"
    ports:
      - "8080:15672"
      - "5672:5672"
    volumes:
      - /data/rabbitmq:/var/lib/rabbitmq
    state: present

- name: Start Rabbitmq container
  docker_container:
    name: rabbitmq-node1
    image: rabbitmq:3-management
    state: started
  when: "'floating_ip' in group_names"

# - name: Start rabbitmq container node2
#   docker_container:
#     name: rabbitmq-node2
#     image: rabbitmq:3-management
#     env:
#       RABBITMQ_ERLANG_COOKIE: "secret_cookie"
#     networks: 
#       - name: rabbitmq
